[[permission]]
identifier = "allow-get-group"
description = "Enables the get_group command without any pre-configured scope."
commands.allow = ["get_group"]

[[permission]]
identifier = "deny-get-group"
description = "Denies the get_group command without any pre-configured scope."
commands.deny = ["get_group"]
