[[permission]]
identifier = "allow-get-snippets"
description = "Enables the get_snippets command."
commands.allow = ["get_snippets"]

[[permission]]
identifier = "allow-add-snippet"
description = "Enables the add_snippet command."
commands.allow = ["add_snippet"]

[[permission]]
identifier = "allow-delete-snippet"
description = "Enables the delete_snippet command."
commands.allow = ["delete_snippet"]

[[permission]]
identifier = "allow-get-credentials"
description = "Enables the get_credentials command."
commands.allow = ["get_credentials"]

[[permission]]
identifier = "allow-add-credential"
description = "Enables the add_credential command."
commands.allow = ["add_credential"]

[[permission]]
identifier = "allow-delete-credential"
description = "Enables the delete_credential command."
commands.allow = ["delete_credential"]

[[permission]]
identifier = "allow-update-credential"
description = "Enables the update_credential command."
commands.allow = ["update_credential"]
