[[permission]]
identifier = "allow-update-group"
description = "Enables the update_group command without any pre-configured scope."
commands.allow = ["update_group"]

[[permission]]
identifier = "deny-update-group"
description = "Denies the update_group command without any pre-configured scope."
commands.deny = ["update_group"]
